# Source matugen-generated colors
source = ~/.config/hypr/hyprlock-colors.conf

general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = ~/Resimler/anime-boy-dragon-purple-desktop-wallpaper.jpg  # Burayı kendi duvar kağıdınla değiştir
    color = $hyprlock_bg_color
    blur_passes = 3 # 0 yaparsan blur kapanır
}

image {
    monitor =
    path = ~/Resimler/Reo.png
    size = 600
    rounding = 0 # no rounding
    border_size = 0
    position = -660,-78
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = $hyprlock_outer_color
    inner_color = $hyprlock_inner_color
    font_color = $hyprlock_font_color
    fade_on_empty = true
    placeholder_text = <i>Şifre giriniz...</i>
    hide_input = false
    position = 500, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = $hyprlock_label_color
    font_size = 32
    font_family = Adwaita Sans
    position = 850, 500
    halign = center
    valign = center
}

label {
    monitor = 
    text = $USER
    color = $hyprlock_label_color
    font_size = 64
    font_family = Red Hat Text
    position = 500, 100
}