################################################################################
# PROGRAMS CONFIGURATION
################################################################################
# Define your default applications
# https://wiki.hypr.land/Configuring/Keywords/

$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun

# Additional program variables you can define:
# $browser = firefox
# $editor = code
