################################################################################
# AUTOSTART CONFIGURATION
################################################################################
# Applications to launch at startup

exec-once = waybar & hyprpaper &

exec-once = swayosd-server

# Additional autostart examples:
# exec-once = nm-applet &
# exec-once = blueman-applet &
# exec-once = dunst &
# exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
